<?php

namespace Database\Seeders;

use App\Models\ChecklistTemplate;
use App\Models\ChecklistTemplateItem;
use App\Models\User;
use Illuminate\Database\Seeder;

class ChecklistTemplateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get the first admin user or create a system user
        $systemUser = User::first() ?? User::factory()->create([
            'name' => 'System',
            'email' => 'system@genealogy.local',
        ]);

        $templates = [
            [
                'name' => 'Basic Person Research',
                'description' => 'Essential research steps for documenting a person\'s life',
                'category' => 'general',
                'difficulty_level' => 'beginner',
                'estimated_time' => 180,
                'is_public' => true,
                'is_default' => true,
                'tags' => ['basic', 'person', 'essential'],
                'items' => [
                    [
                        'title' => 'Gather known information',
                        'description' => 'Collect all known facts about the person from family sources',
                        'category' => 'research',
                        'order' => 1,
                        'is_required' => true,
                        'estimated_time' => 30,
                        'resources' => ['Family documents', 'Photos', 'Letters'],
                        'tips' => ['Start with what you know', 'Interview family members', 'Document sources'],
                    ],
                    [
                        'title' => 'Search vital records',
                        'description' => 'Look for birth, marriage, and death certificates',
                        'category' => 'research',
                        'order' => 2,
                        'is_required' => true,
                        'estimated_time' => 60,
                        'resources' => ['State vital records offices', 'FamilySearch', 'Ancestry.com'],
                        'tips' => ['Check multiple spellings', 'Look in neighboring counties', 'Consider name changes'],
                    ],
                    [
                        'title' => 'Census research',
                        'description' => 'Find the person in available census records',
                        'category' => 'research',
                        'order' => 3,
                        'is_required' => true,
                        'estimated_time' => 45,
                        'resources' => ['FamilySearch', 'Ancestry.com', 'MyHeritage'],
                        'tips' => ['Search every 10 years', 'Check neighbors', 'Look for spelling variations'],
                    ],
                    [
                        'title' => 'Document sources',
                        'description' => 'Create proper citations for all sources found',
                        'category' => 'documentation',
                        'order' => 4,
                        'is_required' => true,
                        'estimated_time' => 30,
                        'resources' => ['Evidence Explained book', 'Citation templates'],
                        'tips' => ['Include all source details', 'Note where you found it', 'Save digital copies'],
                    ],
                    [
                        'title' => 'Verify information',
                        'description' => 'Cross-reference facts with multiple sources',
                        'category' => 'verification',
                        'order' => 5,
                        'is_required' => false,
                        'estimated_time' => 15,
                        'resources' => ['Multiple independent sources'],
                        'tips' => ['Look for conflicting information', 'Prefer primary sources', 'Note discrepancies'],
                    ],
                ],
            ],
            [
                'name' => 'Vital Records Research',
                'description' => 'Comprehensive search for birth, marriage, and death records',
                'category' => 'vital_records',
                'difficulty_level' => 'intermediate',
                'estimated_time' => 240,
                'is_public' => true,
                'is_default' => true,
                'tags' => ['vital records', 'certificates', 'official documents'],
                'items' => [
                    [
                        'title' => 'Identify vital records offices',
                        'description' => 'Determine which offices hold records for the time and place',
                        'category' => 'research',
                        'order' => 1,
                        'is_required' => true,
                        'estimated_time' => 20,
                        'resources' => ['State vital records websites', 'County clerk offices'],
                        'tips' => ['Check when records started', 'Note office changes', 'Consider religious records'],
                    ],
                    [
                        'title' => 'Search birth records',
                        'description' => 'Look for birth certificates and birth registrations',
                        'category' => 'research',
                        'order' => 2,
                        'is_required' => true,
                        'estimated_time' => 60,
                        'resources' => ['State vital records', 'County records', 'Church records'],
                        'tips' => ['Check delayed registrations', 'Look for hospital records', 'Consider midwife records'],
                    ],
                    [
                        'title' => 'Search marriage records',
                        'description' => 'Find marriage licenses, certificates, and announcements',
                        'category' => 'research',
                        'order' => 3,
                        'is_required' => true,
                        'estimated_time' => 60,
                        'resources' => ['County clerk', 'Church records', 'Newspapers'],
                        'tips' => ['Check both counties', 'Look for banns', 'Search newspapers for announcements'],
                    ],
                    [
                        'title' => 'Search death records',
                        'description' => 'Locate death certificates and burial records',
                        'category' => 'research',
                        'order' => 4,
                        'is_required' => true,
                        'estimated_time' => 60,
                        'resources' => ['State vital records', 'Funeral homes', 'Cemeteries'],
                        'tips' => ['Check coroner records', 'Look for obituaries', 'Find burial permits'],
                    ],
                    [
                        'title' => 'Order certified copies',
                        'description' => 'Request official copies of found records',
                        'category' => 'documentation',
                        'order' => 5,
                        'is_required' => false,
                        'estimated_time' => 30,
                        'resources' => ['Official request forms', 'Payment methods'],
                        'tips' => ['Follow office procedures', 'Include proper fees', 'Provide proof of relationship'],
                    ],
                    [
                        'title' => 'Analyze information',
                        'description' => 'Review records for new leads and verify existing data',
                        'category' => 'analysis',
                        'order' => 6,
                        'is_required' => true,
                        'estimated_time' => 10,
                        'resources' => ['Research log', 'Family tree software'],
                        'tips' => ['Note informants', 'Check for new names', 'Look for address clues'],
                    ],
                ],
            ],
            [
                'name' => 'Census Research Strategy',
                'description' => 'Systematic approach to finding ancestors in census records',
                'category' => 'census',
                'difficulty_level' => 'intermediate',
                'estimated_time' => 300,
                'is_public' => true,
                'is_default' => true,
                'tags' => ['census', 'population', 'enumeration'],
                'items' => [
                    [
                        'title' => 'Identify available census years',
                        'description' => 'Determine which census records exist for your research period',
                        'category' => 'research',
                        'order' => 1,
                        'is_required' => true,
                        'estimated_time' => 15,
                        'resources' => ['Census availability charts', 'FamilySearch Wiki'],
                        'tips' => ['Note destroyed records', 'Check state censuses', 'Consider special censuses'],
                    ],
                    [
                        'title' => 'Search by name',
                        'description' => 'Use name indexes to locate the family',
                        'category' => 'research',
                        'order' => 2,
                        'is_required' => true,
                        'estimated_time' => 60,
                        'resources' => ['Ancestry.com', 'FamilySearch', 'MyHeritage'],
                        'tips' => ['Try spelling variations', 'Use wildcards', 'Search nicknames'],
                    ],
                    [
                        'title' => 'Browse by location',
                        'description' => 'Manually browse enumeration districts if name search fails',
                        'category' => 'research',
                        'order' => 3,
                        'is_required' => false,
                        'estimated_time' => 90,
                        'resources' => ['Enumeration district maps', 'City directories'],
                        'tips' => ['Use known addresses', 'Check neighboring pages', 'Look for relatives'],
                    ],
                    [
                        'title' => 'Analyze household composition',
                        'description' => 'Study all household members for clues',
                        'category' => 'analysis',
                        'order' => 4,
                        'is_required' => true,
                        'estimated_time' => 30,
                        'resources' => ['Census forms and instructions'],
                        'tips' => ['Note relationships', 'Check ages progression', 'Identify boarders'],
                    ],
                    [
                        'title' => 'Research neighbors',
                        'description' => 'Examine neighboring households for relatives',
                        'category' => 'research',
                        'order' => 5,
                        'is_required' => false,
                        'estimated_time' => 45,
                        'resources' => ['Census images', 'Name databases'],
                        'tips' => ['Look for same surnames', 'Check birth places', 'Note migration patterns'],
                    ],
                    [
                        'title' => 'Extract all information',
                        'description' => 'Record all details from the census record',
                        'category' => 'documentation',
                        'order' => 6,
                        'is_required' => true,
                        'estimated_time' => 20,
                        'resources' => ['Census extraction forms', 'Spreadsheets'],
                        'tips' => ['Include occupation details', 'Note immigration info', 'Record property values'],
                    ],
                    [
                        'title' => 'Plan follow-up research',
                        'description' => 'Identify new research leads from census information',
                        'category' => 'follow_up',
                        'order' => 7,
                        'is_required' => true,
                        'estimated_time' => 40,
                        'resources' => ['Research log', 'To-do lists'],
                        'tips' => ['Research new locations', 'Look up occupations', 'Find immigration records'],
                    ],
                ],
            ],
            [
                'name' => 'Immigration Research',
                'description' => 'Finding and analyzing immigration and naturalization records',
                'category' => 'immigration',
                'difficulty_level' => 'advanced',
                'estimated_time' => 360,
                'is_public' => true,
                'is_default' => true,
                'tags' => ['immigration', 'naturalization', 'passenger lists'],
                'items' => [
                    [
                        'title' => 'Gather immigration clues',
                        'description' => 'Collect information about immigration from family sources',
                        'category' => 'research',
                        'order' => 1,
                        'is_required' => true,
                        'estimated_time' => 30,
                        'resources' => ['Family stories', 'Census records', 'Death certificates'],
                        'tips' => ['Note approximate dates', 'Record port of entry', 'Check naturalization status'],
                    ],
                    [
                        'title' => 'Search passenger lists',
                        'description' => 'Look for arrival records in passenger manifests',
                        'category' => 'research',
                        'order' => 2,
                        'is_required' => true,
                        'estimated_time' => 90,
                        'resources' => ['Ancestry.com', 'FamilySearch', 'Ellis Island database'],
                        'tips' => ['Try multiple name spellings', 'Search by ship name', 'Check multiple ports'],
                    ],
                    [
                        'title' => 'Research naturalization records',
                        'description' => 'Find declaration of intention and naturalization papers',
                        'category' => 'research',
                        'order' => 3,
                        'is_required' => true,
                        'estimated_time' => 60,
                        'resources' => ['USCIS', 'Federal courts', 'Local courts'],
                        'tips' => ['Check multiple court levels', 'Look for witnesses', 'Note name changes'],
                    ],
                    [
                        'title' => 'Examine ship manifests',
                        'description' => 'Analyze detailed information from passenger lists',
                        'category' => 'analysis',
                        'order' => 4,
                        'is_required' => true,
                        'estimated_time' => 45,
                        'resources' => ['Original manifest images'],
                        'tips' => ['Read all columns', 'Note traveling companions', 'Check destination addresses'],
                    ],
                    [
                        'title' => 'Research origin locations',
                        'description' => 'Investigate the immigrant\'s place of origin',
                        'category' => 'research',
                        'order' => 5,
                        'is_required' => false,
                        'estimated_time' => 90,
                        'resources' => ['Foreign genealogy websites', 'Church records', 'Local historians'],
                        'tips' => ['Learn local history', 'Understand naming patterns', 'Check religious records'],
                    ],
                    [
                        'title' => 'Document the journey',
                        'description' => 'Create a timeline of the immigration process',
                        'category' => 'documentation',
                        'order' => 6,
                        'is_required' => true,
                        'estimated_time' => 30,
                        'resources' => ['Timeline templates', 'Maps'],
                        'tips' => ['Include all dates', 'Map the journey', 'Note family separations'],
                    ],
                    [
                        'title' => 'Follow up research',
                        'description' => 'Plan additional research based on findings',
                        'category' => 'follow_up',
                        'order' => 7,
                        'is_required' => true,
                        'estimated_time' => 15,
                        'resources' => ['Research plan templates'],
                        'tips' => ['Research traveling companions', 'Look for chain migration', 'Check return visits'],
                    ],
                ],
            ],
            [
                'name' => 'Military Records Research',
                'description' => 'Comprehensive search for military service records',
                'category' => 'military',
                'difficulty_level' => 'intermediate',
                'estimated_time' => 270,
                'is_public' => true,
                'is_default' => true,
                'tags' => ['military', 'service records', 'pension'],
                'items' => [
                    [
                        'title' => 'Identify military service',
                        'description' => 'Determine if and when the person served in the military',
                        'category' => 'research',
                        'order' => 1,
                        'is_required' => true,
                        'estimated_time' => 30,
                        'resources' => ['Family stories', 'Census records', 'Draft registrations'],
                        'tips' => ['Check age during wars', 'Look for military occupations', 'Note veteran status'],
                    ],
                    [
                        'title' => 'Search service records',
                        'description' => 'Look for compiled military service records',
                        'category' => 'research',
                        'order' => 2,
                        'is_required' => true,
                        'estimated_time' => 60,
                        'resources' => ['National Archives', 'Fold3', 'FamilySearch'],
                        'tips' => ['Know the correct war', 'Check unit information', 'Look for multiple enlistments'],
                    ],
                    [
                        'title' => 'Research pension records',
                        'description' => 'Find pension applications and supporting documents',
                        'category' => 'research',
                        'order' => 3,
                        'is_required' => true,
                        'estimated_time' => 60,
                        'resources' => ['National Archives', 'Fold3', 'State archives'],
                        'tips' => ['Check widow pensions', 'Look for medical records', 'Note witness statements'],
                    ],
                    [
                        'title' => 'Search draft registrations',
                        'description' => 'Find World War I and II draft registration cards',
                        'category' => 'research',
                        'order' => 4,
                        'is_required' => false,
                        'estimated_time' => 30,
                        'resources' => ['Ancestry.com', 'FamilySearch', 'National Archives'],
                        'tips' => ['Check all draft periods', 'Note physical descriptions', 'Record employer information'],
                    ],
                    [
                        'title' => 'Research unit history',
                        'description' => 'Learn about the military unit\'s service history',
                        'category' => 'research',
                        'order' => 5,
                        'is_required' => false,
                        'estimated_time' => 45,
                        'resources' => ['Unit histories', 'Battle records', 'Military museums'],
                        'tips' => ['Understand battles fought', 'Learn unit movements', 'Check casualty lists'],
                    ],
                    [
                        'title' => 'Document military timeline',
                        'description' => 'Create a chronology of military service',
                        'category' => 'documentation',
                        'order' => 6,
                        'is_required' => true,
                        'estimated_time' => 30,
                        'resources' => ['Timeline templates', 'Military calendars'],
                        'tips' => ['Include all service dates', 'Note promotions', 'Record locations served'],
                    ],
                    [
                        'title' => 'Plan additional research',
                        'description' => 'Identify follow-up research opportunities',
                        'category' => 'follow_up',
                        'order' => 7,
                        'is_required' => false,
                        'estimated_time' => 15,
                        'resources' => ['Research logs'],
                        'tips' => ['Research fellow soldiers', 'Check local newspapers', 'Look for medals and honors'],
                    ],
                ],
            ],
            [
                'name' => 'DNA Research Strategy',
                'description' => 'Using DNA testing results for genealogical research',
                'category' => 'dna',
                'difficulty_level' => 'advanced',
                'estimated_time' => 420,
                'is_public' => true,
                'is_default' => true,
                'tags' => ['DNA', 'genetic genealogy', 'matches'],
                'items' => [
                    [
                        'title' => 'Analyze DNA matches',
                        'description' => 'Review and categorize DNA test matches',
                        'category' => 'analysis',
                        'order' => 1,
                        'is_required' => true,
                        'estimated_time' => 60,
                        'resources' => ['DNA testing websites', 'Match spreadsheets'],
                        'tips' => ['Start with closest matches', 'Group by shared matches', 'Note shared segments'],
                    ],
                    [
                        'title' => 'Research match trees',
                        'description' => 'Examine family trees of DNA matches',
                        'category' => 'research',
                        'order' => 2,
                        'is_required' => true,
                        'estimated_time' => 90,
                        'resources' => ['Match family trees', 'Genealogy databases'],
                        'tips' => ['Look for common ancestors', 'Note geographic patterns', 'Check tree accuracy'],
                    ],
                    [
                        'title' => 'Build mirror trees',
                        'description' => 'Create research trees for key DNA matches',
                        'category' => 'research',
                        'order' => 3,
                        'is_required' => false,
                        'estimated_time' => 120,
                        'resources' => ['Genealogy software', 'Research databases'],
                        'tips' => ['Focus on unknown lines', 'Document all sources', 'Share findings with matches'],
                    ],
                    [
                        'title' => 'Use chromosome mapping',
                        'description' => 'Map DNA segments to ancestral lines',
                        'category' => 'analysis',
                        'order' => 4,
                        'is_required' => false,
                        'estimated_time' => 60,
                        'resources' => ['Chromosome mapping tools', 'Segment data'],
                        'tips' => ['Start with known relatives', 'Use triangulation', 'Document segment assignments'],
                    ],
                    [
                        'title' => 'Contact DNA matches',
                        'description' => 'Reach out to DNA matches for collaboration',
                        'category' => 'research',
                        'order' => 5,
                        'is_required' => true,
                        'estimated_time' => 45,
                        'resources' => ['Messaging templates', 'Contact logs'],
                        'tips' => ['Be specific about connection', 'Share your research', 'Be patient for responses'],
                    ],
                    [
                        'title' => 'Analyze ethnicity results',
                        'description' => 'Review and understand ethnicity estimates',
                        'category' => 'analysis',
                        'order' => 6,
                        'is_required' => false,
                        'estimated_time' => 30,
                        'resources' => ['Ethnicity reports', 'Population genetics resources'],
                        'tips' => ['Understand limitations', 'Compare with known ancestry', 'Look for unexpected results'],
                    ],
                    [
                        'title' => 'Plan targeted testing',
                        'description' => 'Identify family members who should test',
                        'category' => 'follow_up',
                        'order' => 7,
                        'is_required' => false,
                        'estimated_time' => 15,
                        'resources' => ['Testing strategy guides'],
                        'tips' => ['Test older generations first', 'Consider different companies', 'Plan for specific questions'],
                    ],
                ],
            ],
        ];

        foreach ($templates as $templateData) {
            $items = $templateData['items'];
            unset($templateData['items']);

            $templateData['created_by'] = $systemUser->id;

            $template = ChecklistTemplate::create($templateData);

            foreach ($items as $itemData) {
                $itemData['checklist_template_id'] = $template->id;
                ChecklistTemplateItem::create($itemData);
            }
        }
    }
}