<?php

declare(strict_types=1);

namespace Tests\Unit\Services\Dna;

use App\Services\Dna\RawDnaParser;
use Tests\TestCase;

/**
 * Pure-parsing tests for RawDnaParser — no DB, no RefreshDatabase.
 * Each test writes a tiny raw-DNA file to the system temp dir, parses it,
 * and asserts the normalized kit map. Temp files are removed in tearDown.
 */
class RawDnaParserTest extends TestCase
{
    /** @var list<string> */
    private array $tempFiles = [];

    protected function tearDown(): void
    {
        foreach ($this->tempFiles as $file) {
            @unlink($file);
        }

        parent::tearDown();
    }

    public function test_it_parses_23andme_tab_separated_and_drops_no_calls(): void
    {
        $path = $this->writeTemp(implode("\n", [
            '# This data file generated by 23andMe at: Wed Jan 01 00:00:00 2020',
            '# rsid	chromosome	position	genotype',
            "rs1\t1\t82154\tAG",
            "rs2\t1\t82170\tCC",
            "rs3\tX\t100\tG",        // single allele → GG
            "rs4\t2\t500\t--",       // no-call → dropped
            '',                       // blank line → ignored
        ]));

        $map = (new RawDnaParser())->parse($path);

        $this->assertSame([
            '1' => [82154 => 'AG', 82170 => 'CC'],
            'X' => [100 => 'GG'],
        ], $map);
    }

    public function test_it_parses_ancestrydna_split_alleles_and_sorts_genotypes(): void
    {
        $path = $this->writeTemp(implode("\n", [
            '#AncestryDNA raw data download',
            "rsid\tchromosome\tposition\tallele1\tallele2",
            "rs1\t1\t82154\tG\tA",   // combined + sorted → AG
            "rs2\t23\t555\tC\tC",    // chromosome 23 → X, CC
            "rs3\t2\t900\t0\t0",     // no-call → dropped
            "rs4\t2\t950\tD\tD",     // indel no-call → dropped
        ]));

        $map = (new RawDnaParser())->parse($path);

        $this->assertSame([
            '1' => [82154 => 'AG'],
            'X' => [555 => 'CC'],
        ], $map);
    }

    public function test_it_parses_myheritage_quoted_csv(): void
    {
        $path = $this->writeTemp(implode("\n", [
            '# MyHeritage DNA raw data.',
            '"RSID","CHROMOSOME","POSITION","RESULT"',
            '"rs1","1","82154","GA"',   // sorted → AG
            '"rs2","MT","16","TT"',
        ]));

        $map = (new RawDnaParser())->parse($path);

        $this->assertSame([
            '1' => [82154 => 'AG'],
            'MT' => [16 => 'TT'],
        ], $map);
    }

    public function test_it_returns_empty_array_for_missing_file(): void
    {
        $this->assertSame([], (new RawDnaParser())->parse('/no/such/file.txt'));
    }

    public function test_parse_content_parses_an_in_memory_string(): void
    {
        $raw = implode("\n", [
            '# This data file generated by 23andMe at: Wed Jan 01 00:00:00 2020',
            "rs1\t1\t82154\tAG",
            "rs2\tX\t100\tG",   // single allele → GG
            "rs3\t2\t500\t--",  // no-call → dropped
        ]);

        $map = (new RawDnaParser())->parseContent($raw);

        $this->assertSame([
            '1' => [82154 => 'AG'],
            'X' => [100 => 'GG'],
        ], $map);
    }

    private function writeTemp(string $contents): string
    {
        $path = tempnam(sys_get_temp_dir(), 'rawdna_');
        file_put_contents($path, $contents);
        $this->tempFiles[] = $path;

        return $path;
    }
}
