// ... existing code ...
<form method="POST" action="{{ route('admin.login') }}">
    @csrf
    <!-- Add a hidden CSRF token field as a backup -->
    <input type="hidden" name="_token" value="{{ csrf_token() }}">
    
    // ... rest of the form fields ...
</form>
// ... existing code ...