<?php

declare(strict_types=1);

namespace Tests\Feature\Services;

use App\Services\AdvancedDnaMatchingService;
use Illuminate\Support\Facades\Storage;
use Tests\TestCase;

/**
 * End-to-end check of the rebuilt (C7) DNA pipeline: two raw kit files on the
 * private disk are parsed (RawDnaParser), matched (SegmentMatcher), and scored
 * (RelationshipEstimator) — proving the advanced path actually runs instead of
 * silently falling back. Two identical kits with a long half-identical run on
 * chr1 must yield a real segment and a real (non-fallback) relationship label.
 */
class DnaMatchingPipelineTest extends TestCase
{
    public function test_advanced_matching_runs_the_real_pipeline_on_parsed_kits(): void
    {
        Storage::fake('private');

        $kit = $this->buildKit();
        Storage::disk('private')->put('kit_a.txt', $kit);
        Storage::disk('private')->put('kit_b.txt', $kit);

        $result = (new AdvancedDnaMatchingService)
            ->performAdvancedMatching('a', 'kit_a.txt', 'b', 'kit_b.txt');

        // The advanced pipeline ran (not the "Unknown (Basic Analysis)" fallback).
        $this->assertNotSame('Unknown (Basic Analysis)', $result['predicted_relationship']);
        $this->assertGreaterThan(0, $result['total_cms']);
        $this->assertGreaterThanOrEqual(1, $result['shared_segments_count']);
        $this->assertNotEmpty($result['ibd_segments']);
        $this->assertSame('1', $result['ibd_segments'][0]['chromosome']);
        $this->assertTrue($result['comparison_performed']);
    }

    public function test_missing_kit_files_degrade_to_basic_without_throwing(): void
    {
        Storage::fake('private');

        $result = (new AdvancedDnaMatchingService)
            ->performAdvancedMatching('a', 'nope_a.txt', 'b', 'nope_b.txt');

        $this->assertSame('Unknown (Basic Analysis)', $result['predicted_relationship']);
        $this->assertSame(0.0, $result['total_cms']);
        // The zeros above are placeholders for "unknown", and callers rely on
        // this flag to tell them apart from a measured absence of shared DNA.
        $this->assertFalse($result['comparison_performed']);
    }

    /**
     * A 23andMe-format kit: 600 SNPs on chr1 (clears SegmentMatcher's MIN_SNPS)
     * spanning ~18 Mb (clears MIN_CM), all heterozygous AG so two copies are
     * fully half-identical along the whole run.
     */
    private function buildKit(): string
    {
        $lines = [
            '# This data file generated by 23andMe',
            "rsid\tchromosome\tposition\tgenotype",
        ];

        for ($i = 0; $i < 600; $i++) {
            $pos = 1_000_000 + $i * 30_000;
            $lines[] = "rs{$i}\t1\t{$pos}\tAG";
        }

        return implode("\n", $lines)."\n";
    }
}
