<?php

declare(strict_types=1);

namespace Tests\Feature\Services;

use App\Jobs\DnaMatching;
use App\Models\Dna;
use App\Models\User;
use App\Services\AdvancedDnaMatchingService;
use App\Services\Dna\DnaFileVault;
use App\Services\DnaImportService;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Bus;
use Illuminate\Support\Facades\Storage;
use Tests\TestCase;

/**
 * DNA privacy (SCOPE §20): raw kit files are encrypted at rest and matching
 * only runs for kits whose owner consented.
 */
class DnaPrivacyTest extends TestCase
{
    use RefreshDatabase;

    public function test_import_encrypts_the_raw_file_at_rest_and_records_consent(): void
    {
        Storage::fake('private');
        Bus::fake();
        $user = User::factory()->create();

        $path = 'dna-uploads/kit.txt';
        Storage::disk('private')->put($path, $this->kitContent());

        $result = app(DnaImportService::class)->importSingleKit($path, $user->id, true, true);

        // On-disk file is no longer the plaintext (it's ciphertext).
        $onDisk = Storage::disk('private')->get($path);
        $this->assertStringNotContainsString('rs0', $onDisk);
        // ...but the vault decrypts it back to the original.
        $this->assertStringContainsString('rs0', app(DnaFileVault::class)->read($path));

        $this->assertTrue(Dna::find($result['dna_id'])->hasConsent());
        Bus::assertDispatched(DnaMatching::class);
    }

    public function test_import_without_consent_does_not_dispatch_matching(): void
    {
        Storage::fake('private');
        Bus::fake();
        $user = User::factory()->create();

        $path = 'dna-uploads/kit.txt';
        Storage::disk('private')->put($path, $this->kitContent());

        $result = app(DnaImportService::class)->importSingleKit($path, $user->id, true, false);

        $this->assertFalse(Dna::find($result['dna_id'])->hasConsent());
        Bus::assertNotDispatched(DnaMatching::class);
    }

    public function test_matching_reads_and_decrypts_encrypted_kits(): void
    {
        Storage::fake('private');
        $vault = app(DnaFileVault::class);
        $vault->store($this->kitContent(), 'a.txt');
        $vault->store($this->kitContent(), 'b.txt');

        $result = app(AdvancedDnaMatchingService::class)
            ->performAdvancedMatching('a', 'a.txt', 'b', 'b.txt');

        // Parsed the decrypted content and ran the real pipeline, not the fallback.
        $this->assertNotSame('Unknown (Basic Analysis)', $result['predicted_relationship']);
        $this->assertGreaterThan(0, $result['total_cms']);
    }

    private function kitContent(): string
    {
        $lines = ['# This data file generated by 23andMe', "rsid\tchromosome\tposition\tgenotype"];
        for ($i = 0; $i < 600; $i++) {
            $pos = 1_000_000 + $i * 30_000;
            $lines[] = "rs{$i}\t1\t{$pos}\tAG";
        }

        return implode("\n", $lines) . "\n";
    }
}
