apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: genealogy

resources:
  - namespace.yaml
  - resource-quota.yaml
  - configmap.yaml
  - secret.yaml
  - pvc.yaml
  - deployment.yaml
  - horizon-deployment.yaml
  - reverb-deployment.yaml
  - service.yaml
  - network-policy.yaml
  - ingress.yaml
  - hpa.yaml
  - scheduler-cronjob.yaml

commonLabels:
  app.kubernetes.io/name: genealogy
  app.kubernetes.io/part-of: liberu-genealogy
  app.kubernetes.io/managed-by: kustomize
