apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: genealogy-storage
  namespace: genealogy
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
