apiVersion: v1
kind: Secret
metadata:
  name: genealogy-secrets
  namespace: genealogy
type: Opaque
stringData:
  APP_KEY: "base64:REPLACE_WITH_YOUR_APP_KEY"
  DB_USERNAME: "genealogy"
  DB_PASSWORD: "REPLACE_WITH_DB_PASSWORD"
  REDIS_PASSWORD: ""
  REVERB_APP_ID: "REPLACE_ME"
  REVERB_APP_KEY: "REPLACE_ME"
  REVERB_APP_SECRET: "REPLACE_ME"
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  MAIL_USERNAME: ""
  MAIL_PASSWORD: ""
