<?php

declare(strict_types=1);

namespace Tests\Feature\Console;

use App\Models\Dna;
use App\Models\DnaMatching;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Storage;
use Tests\TestCase;

/**
 * The rebuilt dna:match command. The original never set a user id (so every
 * insert threw) and fabricated centimorgans with random_int() in its catch
 * block. The replacement sets the owning user, persists only when a real
 * comparison ran, exits non-zero when it cannot compare, and never invents a
 * value in an error path.
 */
final class DnaMatchCommandTest extends TestCase
{
    use RefreshDatabase;

    public function test_it_persists_a_match_owned_by_the_base_kit_owner_after_a_real_comparison(): void
    {
        Storage::fake('private');
        Storage::disk('private')->put('kit_a.txt', $this->buildKit());
        Storage::disk('private')->put('kit_b.txt', $this->buildKit());

        $owner = User::factory()->withPersonalTeam()->create();
        $other = User::factory()->withPersonalTeam()->create();
        Dna::factory()->create(['variable_name' => 'a', 'file_name' => 'kit_a.txt', 'user_id' => $owner->id]);
        Dna::factory()->create(['variable_name' => 'b', 'file_name' => 'kit_b.txt', 'user_id' => $other->id]);

        $this->artisan('dna:match', ['kit1' => 'a', 'kit2' => 'b'])->assertSuccessful();

        $row = DnaMatching::withoutGlobalScopes()->firstOrFail();
        $this->assertSame($owner->id, $row->user_id);
        $this->assertSame($other->id, $row->match_id);
        $this->assertSame($owner->current_team_id, $row->team_id);
        $this->assertGreaterThan(0, (float) $row->total_shared_cm);
    }

    public function test_it_persists_nothing_and_exits_non_zero_when_the_kits_cannot_be_compared(): void
    {
        Storage::fake('private'); // no kit files staged -> comparison cannot run

        $owner = User::factory()->withPersonalTeam()->create();
        Dna::factory()->create(['variable_name' => 'a', 'file_name' => 'missing_a.txt', 'user_id' => $owner->id]);
        Dna::factory()->create(['variable_name' => 'b', 'file_name' => 'missing_b.txt', 'user_id' => $owner->id]);

        $this->artisan('dna:match', ['kit1' => 'a', 'kit2' => 'b'])->assertFailed();

        $this->assertDatabaseCount('dna_matchings', 0);
    }

    public function test_it_exits_non_zero_when_a_kit_is_unknown(): void
    {
        $this->artisan('dna:match', ['kit1' => 'nope', 'kit2' => 'nada'])->assertFailed();

        $this->assertDatabaseCount('dna_matchings', 0);
    }

    /**
     * A 23andMe-format kit with a long half-identical run on chr1 — enough to
     * clear SegmentMatcher's thresholds and yield a real segment. Mirrors
     * DnaMatchingPipelineTest's fixture.
     */
    private function buildKit(): string
    {
        $lines = ['# This data file generated by 23andMe', "rsid\tchromosome\tposition\tgenotype"];
        for ($i = 0; $i < 600; $i++) {
            $lines[] = 'rs'.$i."\t1\t".(1_000_000 + $i * 30_000)."\tAG";
        }

        return implode("\n", $lines)."\n";
    }
}
