<?php

use App\Models\User;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

/**
 * Adds the team key to the permission tables so roles can be scoped per team.
 *
 * Adapted from the stub shipped by spatie/laravel-permission
 * (database/migrations/add_teams_fields.php.stub, generated by
 * `php artisan permission:setup-teams`). Two deliberate departures from it, both
 * about the pivot tables, are marked below.
 *
 * Idempotent by column check, and that is load-bearing rather than defensive:
 * create_permission_tables consults permission.teams at run time, so now the
 * flag is on, a fresh database gets these columns from that migration and never
 * reaches the bodies here. An existing database gets them here. The two paths
 * have to converge on the same schema.
 */
return new class extends Migration
{
    public function up(): void
    {
        $tableNames = config('permission.table_names');
        $columnNames = config('permission.column_names');
        $pivotRole = $columnNames['role_pivot_key'] ?? 'role_id';
        $pivotPermission = $columnNames['permission_pivot_key'] ?? 'permission_id';
        $teamKey = $columnNames['team_foreign_key'] ?? null;

        if (! config('permission.teams')) {
            return;
        }

        throw_if(empty($tableNames), 'Error: config/permission.php not loaded. Run [php artisan config:clear] and try again.');
        throw_if(empty($teamKey), 'Error: team_foreign_key on config/permission.php not loaded. Run [php artisan config:clear] and try again.');

        // Role definitions stay global by default. A null team means the role
        // exists in every team, which is what the seeded super_admin is and
        // must remain — scoping it would strip administrators of every team but
        // whichever one happened to be current when the seeder ran.
        if (! Schema::hasColumn($tableNames['roles'], $teamKey)) {
            Schema::table($tableNames['roles'], function (Blueprint $table) use ($teamKey) {
                $table->unsignedBigInteger($teamKey)->nullable()->after('id');
                $table->index($teamKey, 'roles_team_foreign_key_index');

                $table->dropUnique('roles_name_guard_name_unique');
                $table->unique([$teamKey, 'name', 'guard_name']);
            });
        }

        $this->addTeamToPivot(
            $tableNames['model_has_permissions'],
            $teamKey,
            $pivotPermission,
            $columnNames['model_morph_key'],
            $tableNames['permissions'],
            'model_has_permissions_permission_model_type_primary',
            'model_has_permissions_team_foreign_key_index',
        );

        $this->addTeamToPivot(
            $tableNames['model_has_roles'],
            $teamKey,
            $pivotRole,
            $columnNames['model_morph_key'],
            $tableNames['roles'],
            'model_has_roles_role_model_type_primary',
            'model_has_roles_team_foreign_key_index',
        );

        app('cache')
            ->store(config('permission.cache.store') != 'default' ? config('permission.cache.store') : null)
            ->forget(config('permission.cache.key'));
    }

    /**
     * Assignments, unlike definitions, must name a team: the team key joins the
     * primary key, so it cannot be null.
     *
     * FIRST DEPARTURE FROM THE STUB. It adds this column with a hardcoded
     * default of 1, which writes every pre-existing grant to whichever team
     * happens to hold id 1 — a team that need not exist, and whose members need
     * not include the people being granted roles in it. That is the shape of
     * invention this codebase has been removing elsewhere, so it is not used.
     *
     * Instead each existing grant is backfilled to the team its holder was last
     * working in, which is the only team the row carries any evidence for. This
     * narrows previously-global grants to a single team. That is a real change
     * in behaviour and the one the ticket asks for: it removes access rather
     * than inventing it, and an administrator who needs the role in a second
     * team can be granted it there.
     *
     * SECOND DEPARTURE. If any row cannot be resolved that way the migration
     * fails rather than guessing. A grant nobody can attribute to a team is
     * exactly the thing not to paper over.
     */
    private function addTeamToPivot(
        string $table,
        string $teamKey,
        string $pivotKey,
        string $morphKey,
        string $referencedTable,
        string $primaryName,
        string $indexName,
    ): void {
        if (Schema::hasColumn($table, $teamKey)) {
            return;
        }

        Schema::table($table, function (Blueprint $table) use ($teamKey, $indexName) {
            $table->unsignedBigInteger($teamKey)->nullable();
            $table->index($teamKey, $indexName);
        });

        // A correlated subquery rather than an UPDATE ... JOIN: SQLite cannot
        // reference a joined table on the right of SET, so the join form works
        // on MariaDB and fails on the test database. Both dialects accept this.
        //
        // Table names are interpolated, so they are prefixed by hand — the
        // query builder prefixes the tables it is given but not raw fragments,
        // and the two must agree on any install that sets one.
        $prefix = DB::getTablePrefix();
        $users = $prefix.'users';
        $teams = $prefix.'teams';
        $members = $prefix.'team_user';
        $pivot = $prefix.$table;

        // The team must still exist and the holder must still be able to reach
        // it. current_team_id outlives both in this application — removeUser()
        // and a bare detach() leave the column pointing at a team the user is
        // no longer in, which TenantAccessControlTest covers directly — so
        // taking it at face value would scope a grant to a team its holder
        // cannot open, leaving a live row that nothing displays and nobody can
        // revoke. Rows that fail this stay null and are refused below.
        //
        // Reachable means owner OR member: Jetstream does not put an owner in
        // team_user, so a membership-only test would reject every personal
        // team, which is most of them.
        DB::table($table)
            ->where('model_type', User::class)
            ->update([
                $teamKey => DB::raw(
                    "(select u.current_team_id from {$users} u"
                    ." inner join {$teams} t on t.id = u.current_team_id"
                    ." where u.id = {$pivot}.{$morphKey}"
                    .' and (t.user_id = u.id or exists ('
                    ."select 1 from {$members} m where m.team_id = t.id and m.user_id = u.id)))"
                ),
            ]);

        $unresolved = DB::table($table)->whereNull($teamKey)->count();

        throw_if($unresolved > 0, new RuntimeException(
            "Cannot scope {$unresolved} row(s) in {$table} to a team: the holder has no current team, "
            .'or is not a user. Assign each holder a team, or delete the grants, then re-run this migration.'
        ));

        Schema::table($table, function (Blueprint $table) use ($teamKey, $pivotKey, $morphKey, $referencedTable, $primaryName) {
            $table->unsignedBigInteger($teamKey)->nullable(false)->change();

            // SQLite has no ALTER for foreign keys; the driver rebuilds the
            // whole table instead, which carries the constraint across.
            if (DB::getDriverName() !== 'sqlite') {
                $table->dropForeign([$pivotKey]);
            }

            $table->dropPrimary();
            $table->primary([$teamKey, $pivotKey, $morphKey, 'model_type'], $primaryName);

            if (DB::getDriverName() !== 'sqlite') {
                $table->foreign($pivotKey)->references('id')->on($referencedTable)->cascadeOnDelete();
            }
        });
    }

    public function down(): void {}
};
