<?php

declare(strict_types=1);

namespace Tests\Feature\Jobs;

use App\Jobs\DnaMatching;
use App\Models\Dna;
use App\Models\DnaMatching as DM;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Notification;
use Illuminate\Support\Facades\Storage;
use Tests\TestCase;

/**
 * A comparison that did not happen must not be recorded as one that did.
 *
 * When a kit file cannot be read, AdvancedDnaMatchingService does not throw —
 * it logs and returns a zeroed "Unknown (Basic Analysis)" result. The job used
 * to persist that verbatim, producing a durable dna_matchings row (plus a
 * reciprocal row for the other user) for two kits that were never compared.
 * Those rows render in the admin panel next to genuine findings, and a
 * researcher cannot tell that no comparison took place.
 *
 * Zero centimorgans is an honest number. Recording it as a finding is not.
 */
class DnaMatchingNoComparisonTest extends TestCase
{
    use RefreshDatabase;

    public function test_it_persists_nothing_when_the_kits_cannot_be_read(): void
    {
        Storage::fake('private');
        // Delivery is not under test here, and the database channel is
        // separately broken (notifications.id is an integer, but Laravel
        // writes a UUID), which would mask the assertion below.
        Notification::fake();

        // Both kits are consented and present as records, but no file backs
        // either of them, so no segment matching can occur.
        $own = $this->makeKit('a', 'kit_a.txt');
        $this->makeKit('b', 'kit_b.txt');

        (new DnaMatching($own->user, 'a', 'kit_a.txt'))->handle();

        $this->assertDatabaseCount('dna_matchings', 0);
        // Nobody is told about a match that was never computed.
        Notification::assertNothingSent();
    }

    public function test_it_persists_both_directions_when_the_kits_are_readable(): void
    {
        Storage::fake('private');
        // Delivery is not under test here, and the database channel is
        // separately broken (notifications.id is an integer, but Laravel
        // writes a UUID), which would mask the assertion below.
        Notification::fake();

        $kit = $this->buildKit();
        Storage::disk('private')->put('kit_a.txt', $kit);
        Storage::disk('private')->put('kit_b.txt', $kit);

        $own = $this->makeKit('a', 'kit_a.txt');
        $this->makeKit('b', 'kit_b.txt');

        (new DnaMatching($own->user, 'a', 'kit_a.txt'))->handle();

        // One row for each user in the pairing. Guards against the fix
        // suppressing the working path along with the broken one.
        $this->assertDatabaseCount('dna_matchings', 2);

        $match = DM::withoutGlobalScopes()->first();
        $this->assertGreaterThan(0, (float) $match->total_shared_cm);
        $this->assertNotSame('Unknown (Basic Analysis)', $match->predicted_relationship);
    }

    private function makeKit(string $varName, string $fileName): Dna
    {
        return Dna::create([
            'name' => $varName,
            'variable_name' => $varName,
            'file_name' => $fileName,
            'user_id' => User::factory()->create()->id,
            'consent_given' => true,
            'consent_given_at' => now(),
        ]);
    }

    /**
     * A 23andMe-format kit: 600 SNPs on chr1 clearing SegmentMatcher's MIN_SNPS,
     * spanning ~18 Mb to clear MIN_CM, all heterozygous AG so two copies are
     * fully half-identical. Mirrors DnaMatchingPipelineTest's fixture.
     */
    private function buildKit(): string
    {
        $lines = [
            '# This data file generated by 23andMe',
            "rsid\tchromosome\tposition\tgenotype",
        ];

        for ($i = 0; $i < 600; $i++) {
            $pos = 1_000_000 + $i * 30_000;
            $lines[] = "rs{$i}\t1\t{$pos}\tAG";
        }

        return implode("\n", $lines)."\n";
    }
}
