<?php

declare(strict_types=1);

namespace App\Services\Dna;

/**
 * Self-contained parser for consumer raw-DNA export files.
 *
 * Replaces the non-functional vendor php-dna library for the one thing the
 * downstream matcher needs: a normalized "kit map" of
 *   chromosome (string) => [ position (int) => genotype (2-char sorted ACGT) ].
 *
 * Format is auto-detected from the file header using the same signatures as
 * App\Services\DnaImportService::detectFileFormat(); the caller never has to
 * declare it. All supported formats share the column layout
 *   rsid, chromosome, position, genotype[/allele1, allele2]
 * so parsing is a single pass — the only format-specific decision is whether
 * the two alleles arrive in one column (23andMe/MyHeritage/FTDNA) or two
 * (AncestryDNA).
 */
class RawDnaParser
{
    /** Aliases that map onto a canonical chromosome key. */
    private const CHROMOSOME_ALIASES = [
        '23' => 'X',
        '24' => 'Y',
        '26' => 'MT',
        'M' => 'MT',
        // '25' (pseudoautosomal region) is intentionally absent → skipped.
    ];

    /** Canonical chromosome keys we keep. */
    private const VALID_CHROMOSOMES = [
        '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11',
        '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22',
        'X', 'Y', 'MT',
    ];

    /**
     * Parse a raw-DNA file into the normalized kit map.
     *
     * @return array<string, array<int, string>> chromosome => (position => genotype); [] on unreadable/empty input.
     */
    public function parse(string $absoluteFilePath): array
    {
        if ($absoluteFilePath === '' || ! is_file($absoluteFilePath) || ! is_readable($absoluteFilePath)) {
            return [];
        }

        $handle = @fopen($absoluteFilePath, 'rb');
        if ($handle === false) {
            return [];
        }

        $format = null;      // resolved once, from the header; drives allele handling
        $comments = '';      // 23andMe advertises itself in a comment line
        $map = [];

        while (($raw = fgets($handle)) !== false) {
            $line = trim($raw);

            if ($line === '') {
                continue;
            }

            if ($line[0] === '#') {
                $comments .= $line."\n";

                continue;
            }

            // tab vs comma, decided per line so mixed junk can't derail us.
            $delimiter = str_contains($line, "\t") ? "\t" : ',';
            $fields = array_map('trim', str_getcsv($line, $delimiter, '"', ''));

            if ($format === null) {
                $format = $this->detectFormat($comments, $line);
            }

            // Header row (rsid/chromosome/position/...) is not data. It also
            // fails chromosome validation below, but skip it explicitly.
            if (strcasecmp($fields[0] ?? '', 'rsid') === 0) {
                continue;
            }

            if (count($fields) < 4) {
                continue;
            }

            $chromosome = $this->normalizeChromosome($fields[1]);
            if ($chromosome === null) {
                continue;
            }

            if (! ctype_digit($fields[2])) {
                continue;
            }
            $position = (int) $fields[2];

            // AncestryDNA splits the genotype across two allele columns; every
            // other supported format already has both alleles in column 4.
            $genotype = ($format === 'ancestry' && isset($fields[4]))
                ? $fields[3].$fields[4]
                : $fields[3];

            $genotype = $this->normalizeGenotype($genotype);
            if ($genotype === null) {
                continue; // no-call
            }

            $map[$chromosome][$position] = $genotype;
        }

        fclose($handle);

        return $map;
    }

    /**
     * Detect the source format from the header, mirroring
     * DnaImportService::detectFileFormat()'s signatures.
     */
    private function detectFormat(string $comments, string $firstDataLine): string
    {
        if (str_contains($comments, 'This data file generated by 23andMe')) {
            return '23andme';
        }

        if (str_contains($firstDataLine, 'rsid') && str_contains($firstDataLine, 'chromosome')) {
            return 'ancestry';
        }

        if (str_contains($firstDataLine, 'RSID') && str_contains($firstDataLine, 'Chr')) {
            return 'myheritage';
        }

        if (str_contains($firstDataLine, 'RSID') && str_contains($firstDataLine, 'CHROMOSOME')) {
            return 'ftdna';
        }

        return 'generic';
    }

    /**
     * Normalize a chromosome token to a canonical key, or null to skip it.
     */
    private function normalizeChromosome(string $value): ?string
    {
        $chr = strtoupper(trim($value));

        if (str_starts_with($chr, 'CHR')) {
            $chr = substr($chr, 3);
        }

        $chr = self::CHROMOSOME_ALIASES[$chr] ?? $chr;

        return in_array($chr, self::VALID_CHROMOSOMES, true) ? $chr : null;
    }

    /**
     * Normalize a genotype to a 2-char sorted uppercase ACGT string,
     * or null for no-calls / anything non-ACGT.
     */
    private function normalizeGenotype(string $value): ?string
    {
        $g = strtoupper(trim($value));

        if (strlen($g) === 1) {
            $g .= $g; // single allele reported → homozygous
        }

        if (! preg_match('/^[ACGT]{2}$/', $g)) {
            return null; // drops '--', '00', 'DD', 'II', '__', '', indels, etc.
        }

        return $g[0] <= $g[1] ? $g : $g[1].$g[0]; // sort the two alleles
    }
}
