<?php

namespace Tests\Unit\Services;

use App\Models\Dna;
use App\Models\User;
use App\Services\DnaImportService;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Storage;
use Tests\TestCase;

class DnaImportServiceTest extends TestCase
{
    use RefreshDatabase;

    protected DnaImportService $service;

    protected function setUp(): void
    {
        parent::setUp();
        $this->service = new DnaImportService();
        Storage::fake('private');
    }

    public function test_generates_unique_variable_name(): void
    {
        // Create a DNA record with a specific variable name
        Dna::factory()->create(['variable_name' => 'var_test1']);

        // Call the protected method via reflection
        $reflection = new \ReflectionClass($this->service);
        $method = $reflection->getMethod('generateUniqueVarName');
        $method->setAccessible(true);

        $varName = $method->invoke($this->service);

        $this->assertStringStartsWith('var_', $varName);
        $this->assertEquals(9, strlen($varName)); // var_ + 5 random chars
        $this->assertNotEquals('var_test1', $varName);
    }

    public function test_validates_file_format_23andme(): void
    {
        // Create a mock 23andMe file
        $content = "# This data file generated by 23andMe at: Sat Jan 01 12:00:00 2024\n";
        $content .= "rsid\tchromosome\tposition\tgenotype\n";
        $content .= "rs12345\t1\t1000000\tAA\n";
        
        Storage::disk('private')->put('test_23andme.txt', $content);

        $result = $this->service->validateDnaFile('test_23andme.txt');

        $this->assertTrue($result['valid']);
        $this->assertEquals('23andme', $result['format']);
    }

    public function test_validates_file_format_ancestry(): void
    {
        $content = "rsid\tchromosome\tposition\tallele1\tallele2\n";
        $content .= "rs12345\t1\t1000000\tA\tA\n";
        
        Storage::disk('private')->put('test_ancestry.txt', $content);

        $result = $this->service->validateDnaFile('test_ancestry.txt');

        $this->assertTrue($result['valid']);
        $this->assertEquals('ancestry', $result['format']);
    }

    public function test_rejects_file_too_small(): void
    {
        Storage::disk('private')->put('test_small.txt', 'tiny');

        $result = $this->service->validateDnaFile('test_small.txt');

        $this->assertFalse($result['valid']);
        $this->assertStringContainsString('too small', $result['error']);
    }

    public function test_rejects_non_existent_file(): void
    {
        $result = $this->service->validateDnaFile('non_existent.txt');

        $this->assertFalse($result['valid']);
        $this->assertStringContainsString('not readable', $result['error']);
    }

    public function test_import_single_kit_creates_dna_record(): void
    {
        $user = User::factory()->create();
        
        // Create a valid DNA file
        $content = "# This data file generated by 23andMe\n";
        $content .= "rsid\tchromosome\tposition\tgenotype\n";
        $content .= "rs12345\t1\t1000000\tAA\n";
        
        Storage::disk('private')->put('test_kit.txt', $content);

        $result = $this->service->importSingleKit('test_kit.txt', $user->id, false);

        $this->assertArrayHasKey('dna_id', $result);
        $this->assertArrayHasKey('variable_name', $result);
        $this->assertArrayHasKey('file_name', $result);
        
        $this->assertDatabaseHas('dnas', [
            'id' => $result['dna_id'],
            'user_id' => $user->id,
            'variable_name' => $result['variable_name'],
            'file_name' => 'test_kit.txt',
        ]);
    }

    public function test_import_multiple_kits(): void
    {
        $user = User::factory()->create();
        
        // Create multiple valid DNA files
        $files = ['kit1.txt', 'kit2.txt', 'kit3.txt'];
        foreach ($files as $file) {
            $content = "# This data file generated by 23andMe\n";
            $content .= "rsid\tchromosome\tposition\tgenotype\n";
            $content .= "rs12345\t1\t1000000\tAA\n";
            Storage::disk('private')->put($file, $content);
        }

        $result = $this->service->importMultipleKits($files, $user->id, false);

        $this->assertEquals(3, $result['total']);
        $this->assertCount(3, $result['successful']);
        $this->assertCount(0, $result['failed']);
    }

    public function test_import_statistics(): void
    {
        $user = User::factory()->create();
        
        Dna::factory()->count(3)->create(['user_id' => $user->id]);

        $stats = $this->service->getImportStatistics($user->id);

        $this->assertEquals(3, $stats['total_kits']);
        $this->assertNotNull($stats['oldest_kit']);
        $this->assertNotNull($stats['newest_kit']);
    }

    public function test_detects_file_format_myheritage(): void
    {
        $reflection = new \ReflectionClass($this->service);
        $method = $reflection->getMethod('detectFileFormat');
        $method->setAccessible(true);

        $firstLine = "RSID,Chr,Position,Result\n";
        $secondLine = "rs12345,1,1000000,AA\n";

        $format = $method->invoke($this->service, $firstLine, $secondLine);

        $this->assertEquals('myheritage', $format);
    }

    public function test_detects_file_format_ftdna(): void
    {
        $reflection = new \ReflectionClass($this->service);
        $method = $reflection->getMethod('detectFileFormat');
        $method->setAccessible(true);

        $firstLine = "RSID,CHROMOSOME,POSITION,RESULT\n";
        $secondLine = "rs12345,1,1000000,AA\n";

        $format = $method->invoke($this->service, $firstLine, $secondLine);

        $this->assertEquals('ftdna', $format);
    }
}
